### ISSUE TITLE
Use github actions to run semantic-release and publish to npm

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#166]
We can not longer use circleci for publish the libraries to npm, but need to use githubactions. this is due to security hardening and the way the npm token is distributed.

the following repositories are affected:

- [x] https://github.com/adobe/htlengine
- [x] https://github.com/adobe/helix-cli
- [x] https://github.com/adobe/helix-pipeline
- [x] https://github.com/adobe/git-server
- [x] https://github.com/adobe/helix-simulator
- [x] https://github.com/adobe/helix-shared
- [x] https://github.com/adobe/fastly-native-promises
- [x] https://github.com/adobe/helix-status
- [x] https://github.com/adobe/probot-serverless-openwhisk
- [x] https://github.com/adobe/openwhisk-probot-builder
- [x] https://github.com/adobe/openwhisk-action-builder
- [x] https://github.com/adobe/openwhisk-action-utils
- [x] https://github.com/adobe/openwhisk-action-logger
- [x] https://github.com/adobe/helix-vulcain-filters
- [x] https://github.com/adobe/helix-fetch
- [x] https://github.com/adobe/helix-eslint-config
- [ ] https://github.com/adobe/helix-querybuilder
- [ ] https://github.com/adobe/helix-log
- [x] https://github.com/adobe/helix-qr-code
- [x] https://github.com/adobe/helix-onedrive-cli
- [ ] https://github.com/adobe/helix-testutils
- [x] https://github.com/adobe/helix-documents-support
- [ ] https://github.com/adobe/helix-ctl
- [ ] https://github.com/adobe/helix-epsagon
- [x] https://github.com/adobe/helix-markdown-support
- [ ] https://github.com/adobe/helix-bot-shared
- [ ] https://github.com/adobe/helix-auth-fastly
- [ ] https://github.com/adobe/helix-observation-cli
- [ ] https://github.com/adobe/helix-task-support
- [x] https://github.com/adobe/helix-onedrive-support
- [x] https://github.com/adobe/gh-resolve-ref
- [x] https://github.com/adobe/helix-library

**Comment by tripodsan** [comment]
The conversion is pretty simple. as soon as the org secret is enabled, just add a `release.yaml` to the `.github/workflows` directory with:

```
name: Semantic Release
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm test
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
```

And disable the workflow in the circleci config. if several builds needs to run before the release, see this example:
https://github.com/adobe/htlengine/blob/master/.github/workflows/semantic-release.yaml
