### ISSUE TITLE
[monitoring] move all config from package.json to .circleci/config.yml

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#72]
**Is your feature request related to a problem? Please describe.**
The configuration for the monitoring automation is currently spread across multiple files:
- package.json: limited number of config properties like the name and group of the Statuspage component, New Relic monitor name and group policy
- .circleci/config.yml: invocation of the monitoring command from the [adobe/helix-post-deploy](https://circleci.com/orbs/registry/orb/adobe/helix-post-deploy) orb with additional parameters such as action name (if different from package name), package, namespace etc.

**Describe the solution you'd like**
The monitoring command in the adobe/helix-post-deploy orb supports all config options currently definable in the package.json (and more) as parameters. Having multiple places to maintain this configuration is tedious and error prone. It would therefore be best to consolidate monitoring automation config in a single place: the CircleCI config.

**Describe alternatives you've considered**
We could duplicate all parameters currently supported by the monitoring command in the package.json, and extend the tooling to pick them up. But this would just mean more complexity in the tooling and not solve the root problem of having multiple places to configure monitoring automation.

**Additional context**
Example:
- package.json
```json
 "statuspage": {
    "name": "Google Docs Adapter",
    "group": "Delivery"
  },
  "newrelic": {
    "group_policy": "Delivery Repeated Failure"
  }
```
- .circleci/config.yml:
```yaml
  - helix-post-deploy/monitoring:
      action_name: gdocs2md
```
This would be consolidated to:
- .circleci/config.yml:
```yaml
  - helix-post-deploy/monitoring:
      statuspage_name: Google Docs Adapter
      statuspage_group: Delivery
      newrelic_group_policy: Delivery Repeated Failure
      action_name: gdocs2md
```

**Comment by trieloff** [comment]
Just an idea: we could solve this in a more elegant way with YAML references. We put them at the top of the config, so that editing becomes easier.

**Comment by rofe** [comment]
> we could solve this in a more elegant way with YAML references

Something like this?
```yaml
# near the top
helix-post-deploy/monitoring: &monitoring
    statuspage_name: Helix Exmaple Service
    statuspage_group: Delivery
    newrelic_group_policy: Delivery Repeated Failure

# much further down
    - *monitoring
```
